"""Initial migration

Revision ID: 50ef430687c5
Revises: 
Create Date: 2025-12-22 17:01:30.250654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ef430687c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rq_job_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_rq_job_id'), 'jobs', ['rq_job_id'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_created', 'api_usage', ['created_at'], unique=False)
    op.create_index('idx_api_usage_endpoint_created', 'api_usage', ['endpoint', 'created_at'], unique=False)
    op.create_index('idx_api_usage_status_created', 'api_usage', ['status_code', 'created_at'], unique=False)
    op.create_index('idx_api_usage_user_created', 'api_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_endpoint'), 'api_usage', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_method'), 'api_usage', ['method'], unique=False)
    op.create_index(op.f('ix_api_usage_status_code'), 'api_usage', ['status_code'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('optional_skills', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('ats_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jd_title', 'job_descriptions', ['title'], unique=False)
    op.create_index('idx_jd_user_created', 'job_descriptions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('resume_data', sa.JSON(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('application_count', sa.Integer(), nullable=False),
    sa.Column('total_applications', sa.Integer(), nullable=False),
    sa.Column('interviews', sa.Integer(), nullable=False),
    sa.Column('rejections', sa.Integer(), nullable=False),
    sa.Column('average_ats_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_title', 'resumes', ['title'], unique=False)
    op.create_index('idx_resume_user_created', 'resumes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('skill_gap_severity', sa.String(length=50), nullable=True),
    sa.Column('required_coverage', sa.Float(), nullable=True),
    sa.Column('missing_required_count', sa.Integer(), nullable=True),
    sa.Column('ats_details', sa.JSON(), nullable=True),
    sa.Column('skill_gap_details', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_resume', 'applications', ['resume_id', 'application_date'], unique=False)
    op.create_index('idx_application_status', 'applications', ['status'], unique=False)
    op.create_index('idx_application_user_date', 'applications', ['user_id', 'application_date'], unique=False)
    op.create_index(op.f('ix_applications_job_description_id'), 'applications', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('resume_data', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_resume_created', 'resume_versions', ['resume_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_index('idx_version_resume_created', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_description_id'), table_name='applications')
    op.drop_index('idx_application_user_date', table_name='applications')
    op.drop_index('idx_application_status', table_name='applications')
    op.drop_index('idx_application_resume', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index('idx_resume_user_created', table_name='resumes')
    op.drop_index('idx_resume_title', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_index('idx_jd_user_created', table_name='job_descriptions')
    op.drop_index('idx_jd_title', table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_status_code'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_method'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_endpoint'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_index('idx_api_usage_user_created', table_name='api_usage')
    op.drop_index('idx_api_usage_status_created', table_name='api_usage')
    op.drop_index('idx_api_usage_endpoint_created', table_name='api_usage')
    op.drop_index('idx_api_usage_created', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_rq_job_id'), table_name='jobs')
    op.drop_index('idx_job_status_created', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###

